### ISSUE TITLE
[question] less tab?

### ISSUE THREAD

**Issue by mateusoliveira43** [hhpatel14/labs#18]
On `oadp/bookbag/deploy-template.yaml` line 61, should it be? (one less tab in `name`)
```yaml
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
```
