### ISSUE TITLE
Add development steps

### ISSUE THREAD

**Issue by mateusoliveira43** [hhpatel14/labs#20]
I think would be good to add how to set up bookbag for development in one of the READMEs (basically copy the google doc to it).

For example:

## OADP

Development instructions on how to set up OADP bookbag locally.

Run all commands presented in this section in `oadp/bookbag/` folder.

> **Note:** The yaml files were configured for AWS, if you are in a different provider, change the storageClasses names and CSIDrivers in each one for the ones compatible with your cluster.
>
> To list the storageClasses and CSIDrivers available in your cluster, run
>```
>oc get storageclasses
>oc get csidrivers
>```

### Bookbag

To run OADP bookbag, run
```
oc process -f build-template.yaml | oc apply -f -
oc start-build bookbag --follow --from-dir=../.. && oc process -f deploy-template.yaml | oc apply -f -
```
It takes some minutes (TODO can we put a wait here?)

After it finishes building, get the its route to access the lab
```
oc get route.route.openshift.io/bookbag -o=go-template='http://{{.spec.host | printf "%s\n" }}'
```

TODO is there a live reload method? for development, making changes is too painful

To uninstall OADP bookbag, run
```
oc process -f deploy-template.yaml | oc delete -f -
oc process -f build-template.yaml | oc delete -f -
```

### Applications

To install the applications presented in the bookbag, run
```
oc apply -f apps/nginx-stateless/nginx-stateless-template.yaml
oc apply -f apps/mysql-persistent/mysql-persistent-csi.yaml
oc apply -f apps/minimal-3csivol/minimal-3csivol.yaml
```

> **Note:** For the last application, if your cluster version is <= 4.10, run instead
>```
>oc apply -f apps/minimal-3csivol/minimal-3csivol.yaml && oc adm policy add-scc-to-user privileged -z default -n minimal-3csivol
>```

### OADP Operator

After installing from OperatorHub the following operators
- VolSync `stable-0.7`
- OADP `stable-1.2`

in your cluster, create the following secrets
```
oc create secret generic cloud-credentials -n openshift-adp --from-file cloud=./credentials-velero
```

dm-credential.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-adp
  name: dm-credentials
type: Opaque
stringData:
  #The repository encryption key
  RESTIC_PASSWORD: my-secure-restic-password #????
```

```
oc apply -f dm-credential.yaml
```

And create OADP DPA with the following content

DPA
```yaml
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: example-dpa
  namespace: openshift-adp
spec:
  features:
    dataMover:
      enable: false
      credentialName: dm-credentials
  configuration:
    velero:
      featureFlags:
        - EnableCSI
      defaultPlugins:
        - openshift
        - csi
        - <PROVIDER>
    restic:
      enable: false
  backupLocations:
    - velero:
        default: true
        provider: <PROVIDER>
        backupSyncPeriod: 2m0s
        credential:
          key: cloud
          name: cloud-credentials
        objectStorage:
          bucket: <BUCKET>
          prefix: velero
        config:
          region: <REGION>
          profile: default
  # snapshotLocations:
  #   - velero:
  #       provider: <PROVIDER>
  #       config:
  #         region: <REGION>
  #         profile: default
```
